// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.example.com' | (string & {});
};

export type User = {
    id: string;
    email: string;
    name?: string;
};

export type GetUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/users/{id}';
};

export type GetUserErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetUserResponses = {
    /**
     * A user
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];
