// This file was auto-generated by Fern from our API Definition.

export const ApiEnvironment = {
    Default: "https://api.example.com",
} as const;

export type ApiEnvironment = typeof ApiEnvironment.Default;
